services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - admin
      - backend
    restart: always
    
  backend:
    image: dilini2003/web-application-backend:latest
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://doctoradmin:doctor123@cluster0.omsslkt.mongodb.net
      - CLOUDINARY_NAME=dczshcmtl
      - CLOUDINARY_API_KEY=227591654824287
      - CLOUDINARY_SECRET_KEY=i3MCk2UpnXxwqgbolsjdfb75bkY
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=admin1234
      - JWT_SECRET=doctoradmin
    restart: always

  frontend:
    image: dilini2003/web-application-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://65.0.30.30:4000
    restart: always

  admin:
    image: dilini2003/web-application-admin:latest
    container_name: admin
    ports:
      - "5174:5174"
    environment:
      - VITE_BACKEND_URL=http://65.0.30.30:4000
    restart: always